import React, { useState } from "react";
import {
  CircularProgress,
  Typography,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Grid,
  Button,
  Box,
  Tooltip,
  IconButton,
} from "@mui/material";
import InfoIcon from "@mui/icons-material/Info";

interface Email {
  id: number;
  subject: string;
  sender: string;
  receivedAt: string;
  body?: string; // Summary fetched from the backend
}

interface EmailTableProps {
  emails: Email[];
}

const SummaryPage: React.FC<EmailTableProps> = ({ emails }) => {
  const [selectedEmail, setSelectedEmail] = useState<Email | null>(null);
  const [loading, setLoading] = useState(false);

  const handleSelectEmail = (email: Email) => {
    setLoading(true);
    fetch(`http://localhost:5000/get_email_summary?email_id=${email.id}`)
      .then((response) => response.json())
      .then((data) => {
        setSelectedEmail({ ...email, body: data.summary });
        setLoading(false);
      })
      .catch((error) => {
        console.error("Failed to fetch email summary:", error);
        setLoading(false);
      });
  };

  const handleBackToList = () => {
    setSelectedEmail(null);
  };

  if (loading) {
    return (
      <Box
        display="flex"
        flexDirection={"column"}
        justifyContent="center"
        alignItems="center"
        minHeight="100vh"
      >
        <CircularProgress />
        <Typography variant="subtitle1" sx={{ mt: 2, marginLeft: "10px" }}>
          Loading...
        </Typography> 
      </Box>
    );
  }

  if (selectedEmail) {
    return (
      <Paper elevation={3} sx={{ p: 3 }}>
        <Grid container spacing={2}>
          <Grid item xs={6}>
            <Typography variant="h6">
              <strong>Subject:</strong> {selectedEmail.subject}
            </Typography>
            <Typography variant="subtitle1">
              <strong>From:</strong> {selectedEmail.sender}
            </Typography>
            <Typography variant="subtitle1">
              <strong>Received:</strong> {selectedEmail.receivedAt}
            </Typography>
          </Grid>
          <Grid item xs={6}>
            <Typography variant="body1" sx={{ mt: 2 }}>
              <strong>Summary:</strong>
              <br></br>
              <br></br>
              {selectedEmail.body}
            </Typography>
          </Grid>
        </Grid>
        <Button onClick={handleBackToList} sx={{ mt: 2 }}>
          Back to List
        </Button>
      </Paper>
    );
  }

  if (emails === null) {
    return (
      <>
        <Paper
          elevation={1}
          sx={{ marginBottom: "20px", p: 3, maxWidth: "2000px" }}
        >
          <Typography variant="h5" sx={{ fontWeight: "bold", mb: 1 }}>
            Email Summariser
          </Typography>
          <Typography variant="subtitle1" sx={{ mb: 0 }}>
            Click on an email to view its summary.
            <Tooltip
              title="This summary is generated by a local large language model by Meta LLama 3. Please be assured that your data stays private."
              arrow
            >
              <IconButton sx={{ ml: 0 }}>
                <InfoIcon />
              </IconButton>
            </Tooltip>
          </Typography>
        </Paper>
        <TableContainer component={Paper}>
          <Table>
            <TableHead>
              <TableRow>
                <TableCell sx={{ fontWeight: "bold", fontSize: "20px" }}>
                  Subject
                </TableCell>
                <TableCell
                  align="left"
                  sx={{ fontWeight: "bold", fontSize: "20px" }}
                >
                  Sender
                </TableCell>
                <TableCell
                  align="right"
                  sx={{ fontWeight: "bold", fontSize: "20px" }}
                >
                  Received At
                </TableCell>
              </TableRow>
            </TableHead>
            <TableBody>
              <TableRow>
                <TableCell colSpan={3} align="center">
                  No emails available
                </TableCell>
              </TableRow>
            </TableBody>
          </Table>
        </TableContainer>
      </>
    );
  }

  return (
    <>
      <Paper
        elevation={1}
        sx={{ marginBottom: "20px", p: 3, maxWidth: "2000px" }}
      >
        <Typography variant="h5" sx={{ fontWeight: "bold", mb: 1 }}>
          Email Summariser
        </Typography>
        <Typography variant="subtitle1" sx={{ mb: 0 }}>
          Click on an email to view its summary.
          <Tooltip
            title="This summary is generated by a local large language model by Meta LLama 3. Please be assured that your data stays private."
            arrow
          >
            <IconButton sx={{ ml: 0 }}>
              <InfoIcon />
            </IconButton>
          </Tooltip>
        </Typography>
      </Paper>
      <TableContainer component={Paper}>
        <Table>
          <TableHead>
            <TableRow>
              <TableCell sx={{ fontWeight: "bold", fontSize: "20px" }}>
                Emails
              </TableCell>
              <TableCell
                align="left"
                sx={{ fontWeight: "bold", fontSize: "20px" }}
              >
                Sender
              </TableCell>
              <TableCell
                align="right"
                sx={{ fontWeight: "bold", fontSize: "20px" }}
              >
                Received At
              </TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {emails.map((email: Email) => (
              <TableRow
                key={email.id}
                onClick={() => handleSelectEmail(email)}
                style={{ cursor: "pointer" }}
              >
                <TableCell component="th" scope="row" sx={{ fontSize: "15px" }}>
                  {email.subject}
                </TableCell>
                <TableCell align="left" sx={{ fontSize: "15px" }}>
                  {email.sender}
                </TableCell>
                <TableCell align="right" sx={{ fontSize: "15px" }}>
                  {email.receivedAt}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </TableContainer>
    </>
  );
};

export default SummaryPage;
